name: Publish Web App
env:
  PACKAGE_NAME: "${{ github.sha }}"
on:
  push:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
  pull_request:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest release of NodeJS
      uses: rez0n/actions-github-release@main
      id: node_release
      env:
        token: ${{ REPO_ACCESS_TOKEN_WEB_APP }}
        repository: "mastermole0310/Web-App-by-Python-Flask"
        type: "stable"
        
    - name: Update package.json version
      uses: jossef/action-set-json-field@v2
      with:
        file: my_json.json
        field: Version
        value: ${{ REPO_ACCESS_TOKEN_WEB_APP }}
        
    - name: Build image
      run: docker build . --tag mastermole/my_app:${{ env.Version_name }}.${{ env.PACKAGE_NAME }}
        
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}    
    - name: Push image
      run: |
        docker push mastermole/my_app:${{ env.Version_name }}.${{ env.PACKAGE_NAME }}
      
