name: Publish Web App

on:
  push:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
  pull_request:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    name: Bash@3
    displayName: 'Set version number in package.json'
    inputs:
      targetType: 'inline'
      script: sed -i "s/0.0.1/$GITVERSIONNUMBER/g" package.json
    env:
      GITVERSIONNUMBER: $(GitVersion.SemVer)
  
    name: Login to DockerHub
    uses: docker/login-action@v1 
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
       
    name: Build the Docker image
    run: docker build . --file Dockerfile --tag mastermole/web_app:${{ env.VERSION_FRAGMENT }}.${{ env.DEPLOY_PACKAGE_NAME }}
   
    
    name: Push to the DockerHub
    run: docker push mastermole/web_app:${{ env.VERSION_FRAGMENT }}.${{ env.DEPLOY_PACKAGE_NAME }}
