name: ci

on:
  schedule:
    - cron: '* 1 * * *'
  push:
    branches:
      - 'main'
      - 'web_app'
  pull_request:
    branches:
      - 'main'
      - 'web_app'   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    -
      uses: actions/checkout@v2
    -
      name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3 
      with:
        token: ${{secrets.github_token}}    
    -    
      name: Build Docker image
      run: docker build . --tag mastermole/web_app:${{ secrets.MAJOR }}.${{ secrets.MINOR }}.${{ secrets.PATCH }}.${{ steps.buildnumber.outputs.build_number }}
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    -
      name: Push to the DockerHub
      run: docker push mastermole/web_app:${{ secrets.MAJOR }}.${{ secrets.MINOR }}.${{ secrets.PATCH }}.${{ steps.buildnumber.outputs.build_number }}
    -
      name: Update Minor version
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'PATCH'
        value: $((${{ secrets.PATCH }}+1))
        repository: mastermole0310/web_app
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
