name: Publish Web App
on:
  push:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
  pull_request:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
    
          
                                                   
jobs:
   build:
    runs-on: ubuntu-latest
    steps:  
  
     - uses: actions/checkout@v3
       with:
        fetch-depth: 0



     - name: Generate semver
       id: version-generator
       run: |
        export ARTEFACT_VERSION=$(git describe --long --always)
        echo ::set-output name=ARTEFACT_VERSION::$ARTEFACT_VERSION

           
     
     - name: Update package.json version
       uses: jossef/action-set-json-field@v2
       with: 
         file: my_json.json
         field: Version
         value: ${{ steps.version-generator.outputs.ARTEFACT_VERSION }}
       
         

     - name: Build Docker image
       run: docker build . --tag mastermole/my_flask:${{ steps.version-generator.outputs.ARTEFACT_VERSION }}
    
     - name: Login to DockerHub
       uses: docker/login-action@v1 
       with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
     - name: Push to the DockerHub
       run: docker push mastermole/my_flask:${{ steps.version-generator.outputs.ARTEFACT_VERSION }}
       
           
     - name: Docker pull and run from Docker Hub
       uses: appleboy/ssh-action@master
       with:
             host : ${{ secrets.HOSTNAME  }}
             username : ${{ secrets.USER_NAME  }}
             key: ${{ secrets.AWS_PRIVATE_KEY }}
             port: ${{ secrets.PORT }}
             script: |
               docker pull mastermole/my_flask:${{ steps.version-generator.outputs.ARTEFACT_VERSION }}
               docker stop my_flask
               docker rm my_flask
               docker run -d -p 80:5000 --name my_app mastermole/my_flask:${{ steps.version-generator.outputs.ARTEFACT_VERSION }}  
