name: Publish Web App
env:
  PACKAGE_NAME: "${{ github.sha }}"
on:
  push:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
  pull_request:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Gets semantic release info
      id: semantic_release_info
      uses: jossef/action-semantic-release-info@v1
      env: |
        PACKAGE_NAME: "${{ github.sha }}"
        Version_name: "${{ steps.semantic_release_info.outputs.git_tag }}
        
        
    - name: Update package.json version
      uses: jossef/action-set-json-field@v2
      with:
        file: my_json.json
        field: Version
        value: ${{ env.Version_name }}.${{ env.PACKAGE_NAME }}
        
    - name: Build image
      run: docker build . --tag mastermole/my_app:${{ env.Version_name }}.${{ env.PACKAGE_NAME }}
        
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}    
    - name: Push image
      run: |
        docker push mastermole/my_app:${{ env.Version_name }}.${{ env.PACKAGE_NAME }}
      
