name: Publish Web App
env:
  Package_name: "${{ github.sha }}"

on:
  push:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
  pull_request:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v1
    - name: Gets semantic release info
      id: semantic_release_info
      uses: jossef/action-semantic-release-info@v1
      env:
        GITHUB_TOKEN: ${{ DOCKER_USERNAME }}
    - name: Update package.json version
      uses: jossef/action-set-json-field@v2
      with:
        file: my_json.json
        field: Version
        value: ${{ steps.semantic_release_info.outputs.git_tag }}.${{ env.Package_name }}
        
    - name: Build image
      run: |
        docker build . --tag mastermole/my_app:${{ steps.semantic_release_info.outputs.git_tag }}.${{ env.Package_name }}
        
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}    
    - name: Push image
      run: |
        docker push mastermole/my_app:${{ steps.semantic_release_info.outputs.git_tag }}.${{ env.Package_name }}
      
