name: Publish Web App
on:
  push:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
  pull_request:
    branches:
      - 'main'
      - 'web_app'
jobs:
   build:
    runs-on: ubuntu-latest
    steps:  
    -
      uses: actions/checkout@v2

    - name: Generate semver
      id: version-generator
      run: |
        ARTEFACT_VERSION=$(git describe --long --always | sed -r "s/-(([^-]*-){1}[^-]*)$/.\\1/") 
        echo '::set-output name=ARTEFACT_VERSION::$(git describe --long --always | sed -r "s/-(([^-]*-){1}[^-]*)$/.\\1/")'
    
    - name: Generate semver2
      id: version-generator2
      run: |
        git describe --long --always
        
    
      
      
      
      
    - name: Update package.json version
      uses: jossef/action-set-json-field@v2
      with: 
         file: my_json.json
         field: Version
         value: ${{ steps.version-generator.outputs.ARTEFACT_VERSION }}
       
        
    - name: Build image
      run: |
        docker build --build-arg Build=${{ steps.version-generator.outputs.ARTEFACT_VERSION }} \
        -t mastermole/my_app:${{ steps.version-generator.outputs.ARTEFACT_VERSION }} .
        
       
        
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}    
         
    - name: Push image
      run: docker push mastermole/my_app:${{ steps.version-generator.outputs.ARTEFACT_VERSION }}
            
      
