name: Publish Web App

on:
  push:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
  pull_request:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
env:
  VERSION_FILE_NAME: 'VERSION'
  DEPLOY_PACKAGE_NAME: "${{ github.sha }}"
jobs:
  calculate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get version fragment to bump
        id: getVersionFragment
        run: |
          read -r versionFragment < ${{ env.DEPLOY_PACKAGE_NAME }}
          echo "'$versionFragment' version will be incremented"
          echo "::set-env name=VERSION_FRAGMENT::${versionFragment}"

      - name: Generate versions
        uses: HardNorth/github-version-generate@v1.1.2
        with:
          version-source: file
          version-file: ${{ env.VERSION_FILE_NAME }}
          next-version-increment-patch: ${{ contains(env.VERSION_FRAGMENT, 'patch') }}
          next-version-increment-minor: ${{ contains(env.VERSION_FRAGMENT, 'minor') }}
          next-version-increment-major: ${{ contains(env.VERSION_FRAGMENT, 'major') }}
  
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
       
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag mastermole/web_app:${{ env.VERSION_FRAGMENT }}.${{ env.DEPLOY_PACKAGE_NAME }}.
   
    
      - name: Push to the DockerHub
        run: docker push mastermole/web_app:${{ GitVersion_MajorMinorPatch }}
