name: Publish Web App
on:
  push:
    branches:
      - 'main'
      - 'web_app'
  pull_request:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
jobs:
   build:
    runs-on: ubuntu-latest
    steps:  
    -
      uses: actions/checkout@v2

    - name: Generate semver
      id: version-generator
      run: |
        ARTEFACT_VERSION=$(git describe --long --always | sed -r "s/-(([^-]*-){1}[^-]*)$/.\\1/") 
        echo '::set-output name=ARTEFACT_VERSION::$(git describe --long --always | sed -r "s/-(([^-]*-){1}[^-]*)$/.\\1/")'
    
   
    - name: Generate semver3
      id: version-generator3
      run: |
        echo ${{ steps.version-generator.outputs.ARTEFACT_VERSION }}
        
    - name: Update package.json version
      uses: jossef/action-set-json-field@v2
      with: 
         file: my_json.json
         field: Version
         value:  ${{ env.ARTEFACT_VERSION }}
    
