name: ci
env:
  DEPLOY_PACKAGE_NAME: "${{ github.sha }}"

on:
  push:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
  pull_request:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    -
      uses: actions/checkout@v3
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -    
      name: Build the Docker image
      run: docker build . --file Dockerfile --tag mastermole/web_app:${{ secrets.MAJOR }}.${{ secrets.MINOR }}.${{ secrets.PATCH }}.${{ env.DEPLOY_PACKAGE_NAME }}
   
    -
      name: Push to the DockerHub
      run: docker push mastermole/web_app:${{ secrets.MAJOR }}.${{ secrets.MINOR }}.${{ secrets.PATCH }}.${{ env.DEPLOY_PACKAGE_NAME }}
