name: Publish Web App
env:
  DEPLOY_PACKAGE_NAME: "${{ github.sha }}"

on:
  push:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
  pull_request:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
     - name: Get Git Version
       uses: docker://gittools/gitversion:5.0.2-linux-centos-7-netcoreapp2.2
       with:
         args: /github/workspace /nofetch /exec /bin/sh /execargs "-c \"echo $GitVersion_MajorMinorPatch > /github/workspace/my_json.json\""
  
     - name: Login to DockerHub
       uses: docker/login-action@v1 
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
       
     - name: Build the Docker image
       run: docker build . --file Dockerfile --tag mastermole/web_app:${{ GitVersion_MajorMinorPatch }}
   
    
     - name: Push to the DockerHub
       run: docker push mastermole/web_app:${{ GitVersion_MajorMinorPatch }}
