name: Publish Web App

on:
  push:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
  pull_request:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v1
    - name: Generate semver
      id: version-generator
      run: |
        ARTEFACT_VERSION=$(git describe --long --always | sed -r "s/-(([^-]*-){1}[^-]*)$/.\\1/") 
        echo '::set-output name=ARTEFACT_VERSION::$(git describe --long --always | sed -r "s/-(([^-]*-){1}[^-]*)$/.\\1/")'
    - name: Build image
      run: |
        docker build --build-arg Build=${{ steps.version-generator.outputs.ARTEFACT_VERSION }} \
        -t mastermole0310/Web_App_by_Python_Flask:${{ steps.version-generator.outputs.ARTEFACT_VERSION }} .
        docker tag mastermole0310/Web_App_by_Python_Flask:${{ steps.version-generator.outputs.ARTEFACT_VERSION }} \
        mastermole0310/Web_App_by_Python_Flask
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}    
    - name: Push image
      run: |
        docker push mastermole/my_best_server:${{ steps.version-generator.outputs.ARTEFACT_VERSION }}
      
