name: Publish Web App

on:
  push:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
  pull_request:
    branches:
      - 'main'
      - 'web_app'
      - 'sash'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    -
      uses: paulhatch/semantic-version@v4.0.2
      with:
       tag_prefix: "v"
       major_pattern: "(MAJOR)"
       minor_pattern: "(MINOR)"
       format: "${major}.${minor}.${patch}-prerelease${increment}"
       change_path: "src/my-service"
       namespace: my-service
       bump_each_commit: false
       search_commit_body: false
       user_format_type: "json"
    -  
      name: Build Docker image
      run: docker build . --tag mastermole/my_best_server:${major}.${minor}.${patch}-prerelease${increment}
    
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    -
      name: Push to the DockerHub
      run: docker push mastermole/my_best_server:${major}.${minor}.${patch}-prerelease${increment}
      
